### ISSUE TITLE
Unable to open UI

### ISSUE THREAD

**Issue by nqbao** [studioml/studio#149]
I tried to install studioml using `pip`, but then i can't open the ui. Below is the stack trace that i get

```
➜  ~ studio ui
studio-ui
Using TensorFlow backend.
Starting Studio UI on port 5000
[2017-08-30 13:57:47,026] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/studio/studio.py", line 32, in dashboard
    return _render('dashboard.html')
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/studio/studio.py", line 446, in _render
    **kwargs
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: dashboard.html
```

Any hint or suggestion how to make this work?

**Comment by pzhokhov** [comment]
looks like html files are not being included into pip package. We'll look into that, in the mean time, try installing it via `git clone https://github.com/studioml/studio && pip install -e studio`

**Comment by nqbao** [comment]
I did, but now i got this error

```
Traceback (most recent call last):
  File "/Users/baonguyen/anaconda/bin/studio-ui", line 4, in <module>
    __import__('pkg_resources').require('studioml==0.0.0')
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/baonguyen/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.13.0 (/Users/baonguyen/anaconda/lib/python2.7/site-packages), Requirement.parse('requests>=2.18.0'), set(['google-cloud-storage']))
```

I'm using anaconda FYI.

**Comment by pzhokhov** [comment]
Two issues for the price of one :) Let me open another one about compatibility with anaconda; I have only been using plain python / virtualenv so far. If anaconda is not critical, try with plain python, if it is - we'll test/fix it out soon, I have already seen people having a similar problem with anaconda.

**Comment by nqbao** [comment]
i will try with plain anaconda and let you know.

**Comment by nqbao** [comment]
If i run `pip install google-cloud-storage` then the UI will work.
Should we fix the version in the requirements.txt?

Below is the list of dependencies

```
pip freeze | grep google-cloud
google-cloud-core==0.27.1
google-cloud-pubsub==0.28.2
google-cloud-storage==1.4.0
```

**Comment by pzhokhov** [comment]
My viewpoint may be a bit naive, but if you run `pip install google-cloud-storage`, would not it have the same effect as having `google-cloud-storage` in the requirements.txt? 
I.e. If the package is not installed, it will install the latest version, and if it is, it will do nothing? 
Do you know what was the version of google-cloud-storage before running `pip install google-cloud-storage`, when studio ui was not working?

**Comment by nqbao** [comment]
I think `requests` has a version conflict here. I already have `requests` installed in my environment, but google cloud storate require requests >= 2.18. There are also other conflict dependencies as well.

Let me try to reproduce the issue and copy  you the actual dependencies.

**Comment by nieoh** [comment]
Similar issues with setuptools
Traceback (most recent call last):
  File "/home/stephanie/Projects/studio/studioenv/bin/studio-run", line 5, in <module>
    from pkg_resources import require
  File "/home/stephanie/Projects/studio/studioenv/local/lib/python2.7/site-packages/pkg_resources.py", line 2720, in <module>
    parse_requirements(__requires__), Environment()
  File "/home/stephanie/Projects/studio/studioenv/local/lib/python2.7/site-packages/pkg_resources.py", line 592, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (setuptools 2.2 (/home/stephanie/Projects/studio/studioenv/lib/python2.7/site-packages), Requirement.parse('setuptools>=34.0.0'))

**Comment by pzhokhov** [comment]
This should be working now, I'll close this issue and let's reopen it if there are further problems.
