### ISSUE TITLE
Json Decoding Error

### ISSUE THREAD

**Issue by jasonzliang** [studioml/studio#161]
This error happens after I submit a large number of experiments (1000+)

```
ERROR:apscheduler.executors.default:Job "FirebaseAuth._update_user (trigger: interval[0:15:00], next run at: 2017-09-02 23:08:28 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/jason/Desktop/tfstudio/local/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/jason/Desktop/studio/studio/auth.py", line 74, in _update_user
    user = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")  
ValueError: No JSON object could be decoded

```

**Comment by jasonzliang** [comment]
I think I fixed this

**Comment by pzhokhov** [comment]
@jasonzliang Since we merged dev and master, could you take a look and kill this issue if it is not relevant anymore? Thanks!
