### ISSUE TITLE
AttributeError: '_NamespacePath' object has no attribute 'sort'

### ISSUE THREAD

**Issue by Mistobaan** [studioml/studio#220]
I just got this trying to install into GAE using python3
```
Collecting configparser (from -r ../requirements.txt (line 1))
  Using cached configparser-3.5.0.tar.gz
Collecting numpy (from -r ../requirements.txt (line 3))
  Using cached numpy-1.13.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting tensorflow (from -r ../requirements.txt (line 4))
  Using cached tensorflow-1.3.0-cp36-cp36m-macosx_10_11_x86_64.whl
Collecting h5py (from -r ../requirements.txt (line 5))
  Downloading h5py-2.7.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.7MB)
    100% |████████████████████████████████| 4.8MB 137kB/s
Collecting pillow (from -r ../requirements.txt (line 6))
  Using cached Pillow-4.2.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting flask (from -r ../requirements.txt (line 8))
  Downloading Flask-0.12.2-py2.py3-none-any.whl (83kB)
    100% |████████████████████████████████| 92kB 5.6MB/s
Collecting jinja2 (from -r ../requirements.txt (line 9))
  Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB)
    100% |████████████████████████████████| 348kB 2.7MB/s
Collecting pyyaml (from -r ../requirements.txt (line 11))
Collecting cma (from -r ../requirements.txt (line 12))
  Downloading cma-2.3.1-py2.py3-none-any.whl (171kB)
    100% |████████████████████████████████| 174kB 3.0MB/s
Collecting apscheduler (from -r ../requirements.txt (line 14))
  Downloading APScheduler-3.3.1-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 5.4MB/s
Collecting pycryptodome (from -r ../requirements.txt (line 15))
  Downloading pycryptodome-3.4.7.tar.gz (6.5MB)
    100% |████████████████████████████████| 6.5MB 106kB/s
Collecting requests (from -r ../requirements.txt (line 16))
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting requests_toolbelt (from -r ../requirements.txt (line 17))
  Downloading requests_toolbelt-0.8.0-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 5.5MB/s
Collecting python_jwt (from -r ../requirements.txt (line 18))
  Downloading python_jwt-2.0.2-py2.py3-none-any.whl
Collecting sseclient (from -r ../requirements.txt (line 19))
  Downloading sseclient-0.0.18.tar.gz
Collecting timeout_decorator (from -r ../requirements.txt (line 20))
  Downloading timeout-decorator-0.4.0.tar.gz
Collecting terminaltables (from -r ../requirements.txt (line 22))
  Downloading terminaltables-3.1.0.tar.gz
Collecting google-api-python-client (from -r ../requirements.txt (line 24))
  Downloading google_api_python_client-1.6.4-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 5.7MB/s
Collecting google-cloud-storage (from -r ../requirements.txt (line 25))
  Downloading google_cloud_storage-1.4.0-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 5.8MB/s
Collecting google-cloud-pubsub (from -r ../requirements.txt (line 26))
  Downloading google_cloud_pubsub-0.28.3-py2.py3-none-any.whl (79kB)
    100% |████████████████████████████████| 81kB 5.5MB/s
Collecting google-gax<=0.15.14 (from -r ../requirements.txt (line 27))
  Downloading google-gax-0.15.14.tar.gz (109kB)
    100% |████████████████████████████████| 112kB 4.9MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/Users/fabriziomilo/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/__init__.py", line 10, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/Users/fabriziomilo/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/extern/__init__.py", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/Users/fabriziomilo/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2985, in <module>
      File "/Users/fabriziomilo/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2971, in _call_aside
      File "/Users/fabriziomilo/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 3013, in _initialize_master_working_set
      File "/Users/fabriziomilo/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2544, in activate
      File "/Users/fabriziomilo/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2118, in declare_namespace
      File "/Users/fabriziomilo/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2058, in _handle_ns
      File "/Users/fabriziomilo/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2087, in _rebuild_mod_path
    AttributeError: '_NamespacePath' object has no attribute 'sort'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/fy/431mzc6j69sdbblvt_g8r8w00000gn/T/pip-build-dr0fuh4i/google-gax/
```

**Comment by Mistobaan** [comment]
seems is connected to this: https://github.com/googleapis/gax-python/issues/192
running 
```
conda install setuptools
```
fixed my issue.
