### ISSUE TITLE
artifacts larger than 2Gb cannot be uploaded via http

### ISSUE THREAD

**Issue by pzhokhov** [studioml/studio#276]
```
Traceback (most recent call last):
  File "/Users/peter.zhokhov/wv/bin/studio-run", line 3, in <module>
    runner.main()
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/studio/runner.py", line 396, in main
    queue_name=runner_args.queue)
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/studio/runner.py", line 566, in submit_experiments
    experiments)]
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/studio/runner.py", line 413, in add_experiment
    db.add_experiment(e)
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/studio/http_provider.py", line 69, in add_experiment
    self._update_artifacts(experiment, artifacts)
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/studio/http_provider.py", line 86, in _update_artifacts
    .put_artifact(art)
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/studio/tartifact_store.py", line 128, in put_artifact
    finish_upload()
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/studio/tartifact_store.py", line 120, in finish_upload
    self._upload_file(key, tar_filename)
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/studio/http_artifact_store.py", line 45, in _upload_file
    data=f.read())
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/peter.zhokhov/wv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 869, in send
    self.sock.sendall(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 721, in sendall
    v = self.send(data[count:])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 687, in send
    v = self._sslobj.write(data)
OverflowError: string longer than 2147483647 bytes
```

**Comment by pzhokhov** [comment]
Fixed by using `data=f` instead of `data=f.read()` in http_provider. Nice and simple :)
