### ISSUE TITLE
Can not start the UI when studio UI is executed

### ISSUE THREAD

**Issue by AAbusnina** [studioml/studio#330]
When I run `studio ui` I get the following error 

```
Starting Studio UI on port 5000
[2018-05-29 15:39:44,580] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/lib/python3.6/site-packages/studio/apiserver.py", line 37, in dashboard
    return _render('dashboard.html')
  File "/anaconda3/lib/python3.6/site-packages/studio/apiserver.py", line 518, in _render
    auth = get_auth(get_auth_config())
  File "/anaconda3/lib/python3.6/site-packages/studio/apiserver.py", line 511, in get_auth_config
    return get_config()['server']['authentication']
KeyError: 'server'
2018-05-29 15:39:44 ERROR  studio.apiserver - Exception on / [GET]
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/lib/python3.6/site-packages/studio/apiserver.py", line 37, in dashboard
    return _render('dashboard.html')
  File "/anaconda3/lib/python3.6/site-packages/studio/apiserver.py", line 518, in _render
    auth = get_auth(get_auth_config())
  File "/anaconda3/lib/python3.6/site-packages/studio/apiserver.py", line 511, in get_auth_config
    return get_config()['server']['authentication']
KeyError: 'server'
```

**Comment by karlmutch** [comment]
It appears that your config.yawl is missing the server section. Please review the examples for server specifications, or post the config you have with aws keys redacted.

**Comment by cypherxtreme** [comment]
i need to run the server on localhost and i get this error too. Please advise what do i change in my default-config.yaml -->

database:
    type: http
    serverUrl: https://zoo.studio.ml
    authentication: github

storage:
    type: gcloud
    bucket: studio-ed756.appspot.com



queue: local

saveMetricsFrequency: 1m
saveWorkspaceFrequency: 1m
verbose: error

cloud:
    gcloud:
        zone: us-east1-c

resources_needed:
    cpus: 2
    ram:  3g
    hdd:  60g
    gpus: 0

sleep_time: 1
worker_timeout: 30

optimizer:
    cmaes_config:
        popsize: 100
        sigma0: 0.25
        load_best_only: false
    load_checkpoint_file:
    visualization: true
    result_dir: "~/Desktop/"
    checkpoint_interval: 0
    termination_criterion:
        generation: 5
        fitness: 999
        skip_gen_thres: 1.0
        skip_gen_timeout: 30

**Comment by AAbusnina** [comment]
Can you please point out where is the examples for server specifications?

**Comment by karlmutch** [comment]
In your case I believe the database section I think should appear something like the following:

```
database:
    type: http
    serverUrl: https://zoo.studio.ml:5000
    authentication:
        type: github            
```

**Comment by conaku** [comment]
I am getting the same error as mentioned in the post and I also tried updating the serverUrl but no success so far .

**Comment by karlmutch** [comment]
Closing due to inactivity.  Please reopen if this remains a problem.  Thanks, Karl
