### ISSUE TITLE
Problem running ui

### ISSUE THREAD

**Issue by AAbusnina** [studioml/studio#332]
This is the error message I get when I try to run "studio ui"

`Starting Studio UI on port 5000
[2018-06-01 13:33:17,426] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/lib/python3.6/site-packages/studio/apiserver.py", line 37, in dashboard
    return _render('dashboard.html')
  File "/anaconda3/lib/python3.6/site-packages/studio/apiserver.py", line 518, in _render
    auth = get_auth(get_auth_config())
  File "/anaconda3/lib/python3.6/site-packages/studio/apiserver.py", line 511, in get_auth_config
    return get_config()['server']['authentication']
KeyError: 'server'`

**Comment by karlmutch** [comment]
Hi,  Can you post your ~/.studioml/config.yaml file.  I suspect that the server section is missing from this file. Thanks

**Comment by karlmutch** [comment]
closed due to inactivity
