### ISSUE TITLE
studioml ui throws error post successful installation for first time

### ISSUE THREAD

**Issue by conaku** [studioml/studio#335]
I installed studioml for first time in my local centos environment and I was trying to launch studio ui . Launch gets errored out and throws below exception . 
^C(studioml) [conaku@localhost ~]$ studio ui
studio-ui
Starting Studio UI on port 5000
 * Serving Flask app "studio.apiserver" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2018-06-13 12:14:42 ERROR  flask.app - Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python3.4/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/conaku/develoment/studioml/studio/studio/apiserver.py", line 37, in dashboard
    return _render('dashboard.html')
  File "/home/conaku/develoment/studioml/studio/studio/apiserver.py", line 518, in _render
    auth = get_auth(get_auth_config())
  File "/home/conaku/develoment/studioml/studio/studio/apiserver.py", line 511, in get_auth_config
    return get_config()['server']['authentication']
KeyError: 'server'
It seems to be authentication error however I did provide my provide github account details . Please suggest the resolution

**Comment by conaku** [comment]
Here is my ~/.studioml/config.yaml file 
database:
    type: http
    serverUrl: https://zoo.studio.ml:5000
    authentication: github

storage:
    type: gcloud
    bucket: studio-ed756.appspot.com



queue: local

saveMetricsFrequency: 1m
saveWorkspaceFrequency: 1m
verbose: error

cloud:
    gcloud:
        zone: us-east1-c

resources_needed:
    cpus: 2
    ram:  3g
    hdd:  60g
    gpus: 0

sleep_time: 1
worker_timeout: 30

optimizer:
    cmaes_config:
        popsize: 100
        sigma0: 0.25
        load_best_only: false
    load_checkpoint_file:
    visualization: true
    result_dir: "~/Desktop/"
    checkpoint_interval: 0
    termination_criterion:
        generation: 5
        fitness: 999
        skip_gen_thres: 1.0
        skip_gen_timeout: 30

**Comment by karlmutch** [comment]
Please re-open this ticket if you are unable to progress after adding the server block.

Thanks,
Karl

**Comment by conaku** [comment]
Thanks . I was able to resolve the issue after adding a server section to config file .
