### ISSUE TITLE
can't run example usage completely locally, storage and database

### ISSUE THREAD

**Issue by adityanatraj** [studioml/studio#343]
I followed the "Example Usage" directions but am not able to get it to run without error (aside: is that expected?).

How i installed it:
```
# switch into some dir
mkdir teststudio && cd teststudio

# created a virtualenv. dont want to poison my computer
virtualenv -p `which python3` env && source env/bin/activate

# install it
pip install --upgrade pip
pip install studioml
```

I then tried to follow the instructions for authentication
> To use studio runner and studio ui in guest mode, in studio/default_config.yaml, uncomment "guest: true" under the database section.

Of course, this doesn't work for a few reasons:
1. the file to actually change is `~/.studioml/config.yaml`
2. there is no commented `guest: true` in the database section
3. even when i add a line `guest: true` to the database section, i get this error when i run `studio run`: 

```
...
  File "/Users/208505/Code/other/tstudio/env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/208505/Code/other/tstudio/env/lib/python3.6/site-packages/studio/apiserver.py", line 37, in dashboard
    return _render('dashboard.html')
  File "/Users/208505/Code/other/tstudio/env/lib/python3.6/site-packages/studio/apiserver.py", line 518, in _render
    auth = get_auth(get_auth_config())
  File "/Users/208505/Code/other/tstudio/env/lib/python3.6/site-packages/studio/apiserver.py", line 511, in get_auth_config
    return get_config()['server']['authentication']
KeyError: 'authentication'
```

So being the great reader I am, I added a server section to the config:
```
server:
  authentication: none
```
which allows me to start up `studio ui`. 
_Note_: I just "guessed" that `none` was an option for `authentication`.

In any case, after doing this, as I navigate around the web-ui I'm immediately seeing:
```
...
  File "/Users/208505/Code/other/tstudio/env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/208505/Code/other/tstudio/env/lib/python3.6/site-packages/studio/apiserver.py", line 171, in get_user_experiments
    user, blocking=True)]
  File "/Users/208505/Code/other/tstudio/env/lib/python3.6/site-packages/studio/http_provider.py", line 200, in get_user_experiments
    self._raise_detailed_error(response)
  File "/Users/208505/Code/other/tstudio/env/lib/python3.6/site-packages/studio/http_provider.py", line 308, in _raise_detailed_error
    raise ValueError(str(request.__dict__))
ValueError: {'_content': b'\n<html><head>\n<meta http-equiv="content-type" content="text/html;charset=utf-8">\n<title>500 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n', '_content_consumed': True, '_next': None, 'status_code': 500, 'headers': {'X-Cloud-Trace-Context': '9e9cee2afae91a6a67db81919d2ace5d', 'Date': 'Fri, 22 Jun 2018 21:02:23 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Server': 'Google Frontend', 'Content-Length': '323'}, 'raw': <urllib3.response.HTTPResponse object at 0x106722128>, 'url': 'https://zoo.studio.ml/api/get_user_experiments', 'encoding': 'UTF-8', 'history': [], 'reason': 'Internal Server Error', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(0, 12, 683187), 'request': <PreparedRequest [POST]>, 'connection': <requests.adapters.HTTPAdapter object at 0x1067cd0b8>}
```

in my terminal, which certainly doesn't make me think it's working appropriately. 

So, I ask:
1. did i install it as expected?
2. did i configure it as expected? (however undocumented it is)
3. is it running as expected?
4. what changes need to be made for me to get it working?

**Comment by karlmutch** [comment]
Hi,  Can you include your ~/.studioml/config.yaml file.

**Comment by adityanatraj** [comment]
```
database:
    type: http
    serverUrl: https://zoo.studio.ml
    authentication: github
    guest: true

server:
    authentication: none

storage:
    type: gcloud
    bucket: studio-ed756.appspot.com


queue: local

saveMetricsFrequency: 1m
saveWorkspaceFrequency: 1m
verbose: error

cloud:
    gcloud:
        zone: us-east1-c

resources_needed:
    cpus: 2
    ram:  3g
    hdd:  60g
    gpus: 0

sleep_time: 1
worker_timeout: 30

optimizer:
    cmaes_config:
        popsize: 100
        sigma0: 0.25
        load_best_only: false
    load_checkpoint_file:
    visualization: true
    result_dir: "~/Desktop/"
    checkpoint_interval: 0
    termination_criterion:
        generation: 5
        fitness: 999
        skip_gen_thres: 1.0
        skip_gen_timeout: 30
```

**Comment by karlmutch** [comment]
I am assuming that github authentication is what you wish to use.

switch the 'none' inside the server: authentication block to read github.  For example

```
server:
  authentication: none
```

**Comment by adityanatraj** [comment]
no, actually i want NO authentication since i'm just exploring it

**Comment by karlmutch** [comment]
If you wish to use the google cloud storage then some form of authentication is needed.

The database might be able to be hosted locally using the studio API server but I have never had that use case.

In theory the use case of all local storage and database locally could be added to StudioML, however StudioML is really a tool for many experiments and experimenters sharing resources and results among each other.  If you have a longer term need for StudioML and would like to use it over a longer period of time with just a single machine please feel free to submit a feature request, or change this ticket to be one.

**Comment by karlmutch** [comment]
Closing due to inactivity.  Please reopen if problems persist.

**Comment by Patechoc** [comment]
Hi,

here is my `~/.studioml/config.yaml` configuration file

```yaml
database:
    type: http
    serverUrl: https://zoo.studio.ml:5000
    authentication: github
    guest: true

server:
  authentication: github

storage:
    type: gcloud
    bucket: studio-ed756.appspot.com



queue: local

saveMetricsFrequency: 1m
saveWorkspaceFrequency: 1m
verbose: error

cloud:
    gcloud:
        zone: us-east1-c

resources_needed:
    cpus: 2
    ram:  3g
    hdd:  60g
    gpus: 0

sleep_time: 1
worker_timeout: 30

optimizer:
    cmaes_config:
        popsize: 100
        sigma0: 0.25
        load_best_only: false
    load_checkpoint_file:
    visualization: true
    result_dir: "~/Desktop/"
    checkpoint_interval: 0
    termination_criterion:
        generation: 5
        fitness: 999
        skip_gen_thres: 1.0
        skip_gen_timeout: 30
```

I do want to authenticate, but it seems not to be working for me either. Here is the error I get:

```shell
$ studio ui
studio-ui
Starting Studio UI on port 5000
 * Serving Flask app "studio.apiserver" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2018-12-21 10:56:20 ERROR  flask.app - Exception on /api/get_user_experiments [POST]
Traceback (most recent call last):
  File "/home/patrick/anaconda3/envs/studio27/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patrick/anaconda3/envs/studio27/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patrick/anaconda3/envs/studio27/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/patrick/anaconda3/envs/studio27/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patrick/anaconda3/envs/studio27/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/patrick/anaconda3/envs/studio27/lib/python2.7/site-packages/studio/apiserver.py", line 171, in get_user_experiments
    user, blocking=True)]
  File "/home/patrick/anaconda3/envs/studio27/lib/python2.7/site-packages/studio/http_provider.py", line 198, in get_user_experiments
    data=json.dumps({"user": user}))
  File "/home/patrick/anaconda3/envs/studio27/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/patrick/anaconda3/envs/studio27/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/patrick/anaconda3/envs/studio27/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/patrick/anaconda3/envs/studio27/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/patrick/anaconda3/envs/studio27/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='zoo.studio.ml', port=5000): Max retries exceeded with url: /api/get_user_experiments (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ffb63a87850>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

so it can not connect to the server `zoo.studio.ml`. 

Is your server down?
What are the possibilities to emulate this server locally or somewhere else?

**Comment by Patechoc** [comment]
@karlmutch responded (thanks again) here: https://github.com/studioml/studio/issues/360#issuecomment-449442454
