### ISSUE TITLE
Using S3 to load json payloads from blob directories causes issue with Python 3

### ISSUE THREAD

**Issue by karlmutch** [studioml/studio#344]
Python 3 has stringent checking on byte arrays vs true strings and this causes code that loads json directly from S3 to swoon.  Stacktrace included.  Fixing on a sentient branch, bugfix/337_tar_failures.

```
2018-06-28 07:52:07 DEBUG  S3ArtifactStore - Tar cmd = tar   -cf /tmp/0d500c41-e0a6-4448-a03c-40593c976344 -C /home/kmutch/studio/examples/kera
s .
2018-06-28 07:52:08 INFO   S3ArtifactStore - tar finished in 1.419090986251831s
2018-06-28 07:52:23 DEBUG  S3Provider - checkpointing experiments/1530197526_27b857f7-5f1c-4aa1-b7c2-3ef09ceba0ee
2018-06-28 07:52:23 INFO   S3Provider - Exception the JSON object must be str, not 'bytes' is caught, sleeping 10s and retrying (attempt 0 of 5
)
2018-06-28 07:52:33 DEBUG  S3Provider - checkpointing experiments/1530197526_27b857f7-5f1c-4aa1-b7c2-3ef09ceba0ee
2018-06-28 07:52:33 INFO   S3Provider - Exception the JSON object must be str, not 'bytes' is caught, sleeping 10s and retrying (attempt 1 of 5
)
2018-06-28 07:52:43 DEBUG  S3Provider - checkpointing experiments/1530197526_27b857f7-5f1c-4aa1-b7c2-3ef09ceba0ee
2018-06-28 07:52:43 INFO   S3Provider - Exception the JSON object must be str, not 'bytes' is caught, sleeping 10s and retrying (attempt 2 of 5
)
2018-06-28 07:52:53 DEBUG  S3Provider - checkpointing experiments/1530197526_27b857f7-5f1c-4aa1-b7c2-3ef09ceba0ee
2018-06-28 07:52:53 INFO   S3Provider - Exception the JSON object must be str, not 'bytes' is caught, sleeping 10s and retrying (attempt 3 of 5
)
2018-06-28 07:53:03 DEBUG  S3Provider - checkpointing experiments/1530197526_27b857f7-5f1c-4aa1-b7c2-3ef09ceba0ee
Traceback (most recent call last):
  File "/home/kmutch/studio/studio/runner.py", line 443, in add_experiment
    db.add_experiment(e)
  File "/home/kmutch/studio/studio/keyvalue_provider.py", line 139, in add_experiment
    logger=self.logger)
  File "/home/kmutch/studio/studio/util.py", line 376, in retry
    raise e
  File "/home/kmutch/studio/studio/util.py", line 373, in retry
    return f()
  File "/home/kmutch/studio/studio/keyvalue_provider.py", line 137, in <lambda>
    retry(lambda: self.checkpoint_experiment(experiment, blocking=True),
  File "/home/kmutch/studio/studio/keyvalue_provider.py", line 233, in checkpoint_experiment
    experiment_dict = self._get(self._get_experiments_keybase() + key)
  File "/home/kmutch/studio/studio/s3_provider.py", line 38, in _get
    return json.loads(response['Body'].read())
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "/home/kmutch/studio/examples/keras/p3/bin/studio-run", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/kmutch/studio/studio/scripts/studio-run", line 3, in <module>
    runner.main()
  File "/home/kmutch/studio/studio/runner.py", line 424, in main
    queue_name=runner_args.queue)
  File "/home/kmutch/studio/studio/runner.py", line 609, in submit_experiments
    experiments)]
  File "/home/kmutch/studio/studio/runner.py", line 605, in <listcomp>
    experiments = [add_experiment(e) for e in
  File "/home/kmutch/studio/studio/runner.py", line 443, in add_experiment
    db.add_experiment(e)
  File "/home/kmutch/studio/studio/keyvalue_provider.py", line 139, in add_experiment
    logger=self.logger)
  File "/home/kmutch/studio/studio/util.py", line 376, in retry
    raise e
  File "/home/kmutch/studio/studio/util.py", line 373, in retry
    return f()
  File "/home/kmutch/studio/studio/keyvalue_provider.py", line 137, in <lambda>
    retry(lambda: self.checkpoint_experiment(experiment, blocking=True),
  File "/home/kmutch/studio/studio/keyvalue_provider.py", line 233, in checkpoint_experiment
    experiment_dict = self._get(self._get_experiments_keybase() + key)
  File "/home/kmutch/studio/studio/s3_provider.py", line 38, in _get
    return json.loads(response['Body'].read())
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by karlmutch** [comment]
Fixed in Issues 331 tar failures branch from the sentient fork
