### ISSUE TITLE
KeyError: 'server' when I attempt to access StudioML at localhost:5000 after 'studio run'

### ISSUE THREAD

**Issue by ijstokes** [studioml/studio#350]
I have installed StudioML from a GH master branch just now.  I have all the dependencies in place.  I have tried turning on guest mode and changed authentication to None (tips I found from searching issues reported by others), however I still get the same error.  After installing StudioML and starting it with `studio run`, I use my browser to access http://localhost:5000 where I then get a ServerError message in my browser and a stack trace in my terminal window (trace below).

Please advise how to proceed or debug further.

```
$ studio-ui
Starting Studio UI on port 5000
 * Serving Flask app "studio.apiserver" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2018-07-27 16:04:43 ERROR  flask.app - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/ijstokes/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ijstokes/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ijstokes/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ijstokes/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/ijstokes/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ijstokes/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ijstokes/anaconda3/lib/python3.6/site-packages/studio/apiserver.py", line 37, in dashboard
    return _render('dashboard.html')
  File "/Users/ijstokes/anaconda3/lib/python3.6/site-packages/studio/apiserver.py", line 518, in _render
    auth = get_auth(get_auth_config())
  File "/Users/ijstokes/anaconda3/lib/python3.6/site-packages/studio/apiserver.py", line 511, in get_auth_config
    return get_config()['server']['authentication']
KeyError: 'server'
```

Here is the top of my `default_config.yaml` file:

```yaml
database:
    guest: true
    type: http
    serverUrl: https://zoo.studio.ml
    authentication: None

storage:
    type: gcloud
    bucket: studio-ed756.appspot.com

queue: local

saveMetricsFrequency: 1m
saveWorkspaceFrequency: 1m
verbose: error

cloud:
    gcloud:
        zone: us-east1-c
```

**Comment by karlmutch** [comment]
Closing due to inactivity
